apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactployment
  labels:
    team: hrdevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:        
        - image: ysfyrdmcl/reacttest:v001
          name:  podreact
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 80
            - containerPort: 3000