apiVersion: apps/v1
kind: Deployment
metadata:
  name: configdeployment
  labels:
    team: hrdevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - image: ysfyrdmcl/hrconfig:v001
          name:  podconfig
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 8888